/**
 * TST-012: Keccak Mode Prover Tests
 *
 * Tests the `{ keccak: true }` proof mode of TwoTreeNoirProver, which produces
 * proofs compatible with the on-chain Solidity HonkVerifier generated by bb.js
 * getSolidityVerifier().
 *
 * bb.js v2.1.8 supports two proof modes:
 * - Default (ZK + Poseidon2): ~508 fields, ~16,256 bytes. Off-chain only.
 * - Keccak (non-ZK + Keccak):  ~229 fields, ~7,328 bytes. On-chain compatible.
 *
 * These modes are NOT interchangeable. A proof generated in one mode MUST be
 * verified with the same mode flag. This test suite validates:
 *
 * 1. Keccak mode produces shorter proofs than default mode
 * 2. Keccak proofs verify with { keccak: true }
 * 3. Keccak proofs FAIL verification without the keccak flag (mode mismatch)
 * 4. Default proofs FAIL verification with the keccak flag (mode mismatch)
 * 5. Both modes produce valid proofs from identical inputs
 *
 * IMPORTANT: These tests require ~150s for WASM init. Use 120_000ms timeout
 * in beforeAll. Full proof generation takes 30-90s per proof.
 *
 * Run with: npx vitest run packages/noir-prover/src/keccak-mode.test.ts
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import {
    hash4,
    hashPair,
    poseidon2Sponge,
    Poseidon2Hasher,
    createSparseMerkleTree,
} from '@voter-protocol/crypto';
import {
    TwoTreeNoirProver,
} from './two-tree-prover';
import type { TwoTreeProofInput, TwoTreeProofResult } from './types';
import {
    DISTRICT_SLOT_COUNT,
    TWO_TREE_PUBLIC_INPUT_COUNT,
} from './types';

// ============================================================================
// Constants
// ============================================================================

/** Circuit depth for keccak tests. Using 18 (smallest) for speed. */
const TEST_DEPTH = 18;

/**
 * Expected proof size ranges per mode.
 * These are approximate -- exact sizes depend on circuit complexity.
 * Keccak proofs are roughly half the size of default proofs.
 */
const KECCAK_MAX_BYTES = 10_000;   // Keccak proofs should be < 10KB
const DEFAULT_MIN_BYTES = 12_000;  // Default proofs should be > 12KB

// ============================================================================
// Valid Input Generation
// ============================================================================

/**
 * Build valid two-tree circuit inputs that satisfy ALL Poseidon2 constraints.
 *
 * This mirrors the circuit's internal computation:
 * 1. user_leaf = H4(user_secret, cell_id, registration_salt, authority_level)
 * 2. district_commitment = poseidon2_sponge_24(districts)
 * 3. cell_map_leaf = H2(cell_id, district_commitment)
 * 4. nullifier = H2(identity_commitment, action_domain)
 * 5. Both Merkle roots computed from the leaves
 *
 * Uses depth-18 trees for minimal test latency.
 */
async function buildValidTwoTreeInputs(): Promise<TwoTreeProofInput> {
    const hasher = await Poseidon2Hasher.getInstance();

    // User secrets (private witnesses)
    const userSecret = 0x1234n;
    const cellId = 67890n;
    const registrationSalt = 0x99n;
    const authorityLevel = 1 as const;
    const identityCommitment = 0xabcdefn;
    const actionDomain = 0x01n;

    // Generate 24 district IDs (positional: slot i = seed * 1000 + i + 1)
    const districts: bigint[] = [];
    for (let i = 0; i < DISTRICT_SLOT_COUNT; i++) {
        districts.push(BigInt(1000 + i + 1));
    }

    // ---- Tree 1: User Tree (standard Merkle) ----

    // Compute user leaf as the circuit does:
    // user_leaf = H4(user_secret, cell_id, registration_salt, authority_level)
    const userLeaf = await hash4(userSecret, cellId, registrationSalt, BigInt(authorityLevel));

    // Build a minimal standard Merkle tree with one leaf at index 0.
    // All other leaves are 0n. The siblings along the path are all 0n
    // (since the tree is nearly empty).
    const userPath: bigint[] = [];
    const userIndex = 0;

    // Build bottom-up: at each level, the sibling of a left-child-only subtree is 0n.
    // We need to compute the correct root by hashing through empty siblings.
    let userNode = userLeaf;
    for (let i = 0; i < TEST_DEPTH; i++) {
        // For index 0, we always go left, so sibling is always on the right.
        // Empty leaves/nodes hash to 0n.
        const sibling = 0n;
        userPath.push(sibling);
        // Standard Merkle: left child, so hash(node, sibling)
        userNode = await hasher.hashPair(userNode, sibling);
    }
    const userRoot = userNode;

    // ---- Tree 2: Cell Map Tree (Sparse Merkle Tree) ----

    // Compute district commitment: poseidon2_sponge_24(districts)
    const districtCommitment = await poseidon2Sponge(districts);

    // Compute cell map leaf: H2(cell_id, district_commitment)
    const cellMapLeaf = await hashPair(cellId, districtCommitment);

    // Build SMT and get proof
    const smt = await createSparseMerkleTree({ depth: TEST_DEPTH });
    await smt.insert(cellId, cellMapLeaf);
    const smtProof = await smt.getProof(cellId);
    const cellMapRoot = await smt.getRoot();

    // Extract SMT path bits from proof (spread to convert readonly arrays to mutable)
    const cellMapPath = [...smtProof.siblings];
    const cellMapPathBits = [...smtProof.pathBits];

    // ---- Nullifier ----
    // nullifier = H2(identity_commitment, action_domain)
    const nullifier = await hashPair(identityCommitment, actionDomain);

    return {
        userRoot,
        cellMapRoot,
        districts,
        nullifier,
        actionDomain,
        authorityLevel,
        userSecret,
        cellId,
        registrationSalt,
        identityCommitment,
        userPath,
        userIndex,
        cellMapPath,
        cellMapPathBits,
    };
}

// ============================================================================
// Unit Tests (No WASM, Mock Backend)
// ============================================================================

describe('Keccak Mode - Unit Tests (Mock Backend)', () => {
    let prover: TwoTreeNoirProver;

    beforeAll(() => {
        prover = new TwoTreeNoirProver({ depth: 20 });
    });

    it('verifyProof passes keccak option to backend', async () => {
        // Track whether verifyProof was called with { keccak: true }
        let capturedOptions: any = undefined;

        const mockBackend = {
            verifyProof: async (_proofData: any, options?: any) => {
                capturedOptions = options;
                return true;
            },
            generateProof: async () => ({ proof: new Uint8Array(), publicInputs: [] }),
            destroy: async () => {},
        };
        (prover as any).backend = mockBackend;
        (prover as any).noir = {};

        const fakeResult: TwoTreeProofResult = {
            proof: new Uint8Array(32),
            publicInputs: Array(TWO_TREE_PUBLIC_INPUT_COUNT).fill('0x0'),
        };

        // Test keccak: true
        await prover.verifyProof(fakeResult, { keccak: true });
        expect(capturedOptions).toEqual({ keccak: true });

        // Test default (no keccak)
        capturedOptions = undefined;
        await prover.verifyProof(fakeResult);
        expect(capturedOptions).toBeUndefined();
    });

    it('verifyProofWithExpectedInputs passes keccak option through', async () => {
        let capturedOptions: any = undefined;

        const mockInputs: TwoTreeProofInput = {
            userRoot: 1n,
            cellMapRoot: 2n,
            districts: Array(DISTRICT_SLOT_COUNT).fill(0n).map((_, i) => BigInt(i + 100)),
            nullifier: 3n,
            actionDomain: 4n,
            authorityLevel: 1,
            userSecret: 42n,
            cellId: 67890n,
            registrationSalt: 11111n,
            identityCommitment: 99999n,
            userPath: Array(20).fill(0n),
            userIndex: 0,
            cellMapPath: Array(20).fill(0n),
            cellMapPathBits: Array(20).fill(0),
        };

        // Build matching public inputs
        const pi = Array(TWO_TREE_PUBLIC_INPUT_COUNT).fill('0x0');
        pi[0] = '0x' + mockInputs.userRoot.toString(16);
        pi[1] = '0x' + mockInputs.cellMapRoot.toString(16);
        for (let i = 0; i < DISTRICT_SLOT_COUNT; i++) {
            pi[2 + i] = '0x' + mockInputs.districts[i].toString(16);
        }
        pi[26] = '0x' + mockInputs.nullifier.toString(16);
        pi[27] = '0x' + mockInputs.actionDomain.toString(16);
        pi[28] = '0x' + BigInt(mockInputs.authorityLevel).toString(16);

        const mockBackend = {
            verifyProof: async (_proofData: any, options?: any) => {
                capturedOptions = options;
                return true;
            },
            generateProof: async () => ({ proof: new Uint8Array(), publicInputs: [] }),
            destroy: async () => {},
        };
        (prover as any).backend = mockBackend;
        (prover as any).noir = {};

        const fakeResult: TwoTreeProofResult = {
            proof: new Uint8Array(32),
            publicInputs: pi,
        };

        await prover.verifyProofWithExpectedInputs(fakeResult, mockInputs, { keccak: true });
        expect(capturedOptions).toEqual({ keccak: true });
    });

    it('generateProof passes keccak option to backend', async () => {
        let capturedOptions: any = undefined;

        const mockBackend = {
            generateProof: async (_witness: any, options?: any) => {
                capturedOptions = options;
                return {
                    proof: new Uint8Array(32),
                    publicInputs: Array(TWO_TREE_PUBLIC_INPUT_COUNT).fill('0x0'),
                };
            },
            verifyProof: async () => true,
            destroy: async () => {},
        };
        const mockNoir = {
            execute: async () => ({ witness: new Map() }),
        };
        (prover as any).backend = mockBackend;
        (prover as any).noir = mockNoir;

        const mockInputs: TwoTreeProofInput = {
            userRoot: 1n,
            cellMapRoot: 2n,
            districts: Array(DISTRICT_SLOT_COUNT).fill(0n).map((_, i) => BigInt(i + 100)),
            nullifier: 3n,
            actionDomain: 4n,
            authorityLevel: 1,
            userSecret: 42n,
            cellId: 67890n,
            registrationSalt: 11111n,
            identityCommitment: 99999n,
            userPath: Array(20).fill(0n),
            userIndex: 0,
            cellMapPath: Array(20).fill(0n),
            cellMapPathBits: Array(20).fill(0),
        };

        // Test keccak: true
        await prover.generateProof(mockInputs, { keccak: true });
        expect(capturedOptions).toEqual({ keccak: true });

        // Test default (no keccak)
        capturedOptions = undefined;
        await prover.generateProof(mockInputs);
        expect(capturedOptions).toBeUndefined();
    });
});

// ============================================================================
// Integration Tests (Real WASM + Barretenberg)
// ============================================================================

describe('Keccak Mode - Integration Tests (Real Proofs)', () => {
    let prover: TwoTreeNoirProver;
    let validInputs: TwoTreeProofInput;
    let defaultProof: TwoTreeProofResult;
    let keccakProof: TwoTreeProofResult;

    beforeAll(async () => {
        // Phase 1: Build valid inputs using crypto package (~5-10s)
        validInputs = await buildValidTwoTreeInputs();

        // Phase 2: Initialize prover with depth-18 circuit (~30-60s WASM init)
        prover = new TwoTreeNoirProver({ depth: TEST_DEPTH, threads: 1 });
        await prover.init();

        // Phase 3: Generate both proof types from the same inputs
        // Default mode (ZK + Poseidon2)
        defaultProof = await prover.generateProof(validInputs);

        // Keccak mode (non-ZK + Keccak, on-chain compatible)
        keccakProof = await prover.generateProof(validInputs, { keccak: true });
    }, 600_000); // 10 minutes total for init + two proofs

    afterAll(async () => {
        if (prover) {
            await prover.destroy();
        }
    });

    // ========================================================================
    // Test 1: Proof size differences
    // ========================================================================

    it('keccak proof is smaller than default proof', () => {
        expect(keccakProof.proof.length).toBeLessThan(defaultProof.proof.length);

        console.log(`[TST-012] Default proof: ${defaultProof.proof.length} bytes`);
        console.log(`[TST-012] Keccak proof:  ${keccakProof.proof.length} bytes`);
        console.log(`[TST-012] Size ratio:    ${(keccakProof.proof.length / defaultProof.proof.length * 100).toFixed(1)}%`);
    });

    it('keccak proof is within expected size range (~7,328 bytes)', () => {
        // Keccak mode: ~229 fields, ~7,328 bytes
        expect(keccakProof.proof.length).toBeLessThan(KECCAK_MAX_BYTES);
        expect(keccakProof.proof.length).toBeGreaterThan(0);
    });

    it('default proof is within expected size range (~16,256 bytes)', () => {
        // Default mode: ~508 fields, ~16,256 bytes
        expect(defaultProof.proof.length).toBeGreaterThan(DEFAULT_MIN_BYTES);
    });

    // ========================================================================
    // Test 2: Both modes share the same public inputs
    // ========================================================================

    it('both modes produce the same public inputs', () => {
        expect(keccakProof.publicInputs).toHaveLength(TWO_TREE_PUBLIC_INPUT_COUNT);
        expect(defaultProof.publicInputs).toHaveLength(TWO_TREE_PUBLIC_INPUT_COUNT);

        // Public inputs are circuit outputs -- they must match regardless of proof mode
        for (let i = 0; i < TWO_TREE_PUBLIC_INPUT_COUNT; i++) {
            expect(keccakProof.publicInputs[i]).toBe(defaultProof.publicInputs[i]);
        }
    });

    // ========================================================================
    // Test 3: Keccak proof verifies with keccak flag
    // ========================================================================

    it('keccak proof verifies with { keccak: true }', async () => {
        const valid = await prover.verifyProof(keccakProof, { keccak: true });
        expect(valid).toBe(true);
    }, 60_000);

    // ========================================================================
    // Test 4: Default proof verifies without keccak flag
    // ========================================================================

    it('default proof verifies without keccak flag', async () => {
        const valid = await prover.verifyProof(defaultProof);
        expect(valid).toBe(true);
    }, 60_000);

    // ========================================================================
    // Test 5: Mode mismatch -- keccak proof fails without keccak flag
    // ========================================================================

    it('keccak proof FAILS verification without keccak flag (mode mismatch)', async () => {
        // A keccak proof verified in default mode should either return false
        // or throw an error (implementation-dependent).
        try {
            const valid = await prover.verifyProof(keccakProof);
            // If no error, it must return false
            expect(valid).toBe(false);
        } catch {
            // Barretenberg may throw on invalid proof format -- this is acceptable
            expect(true).toBe(true);
        }
    }, 60_000);

    // ========================================================================
    // Test 6: Mode mismatch -- default proof fails with keccak flag
    // ========================================================================

    it('default proof FAILS verification with keccak flag (mode mismatch)', async () => {
        // A default proof verified in keccak mode should either return false
        // or throw an error (implementation-dependent).
        try {
            const valid = await prover.verifyProof(defaultProof, { keccak: true });
            // If no error, it must return false
            expect(valid).toBe(false);
        } catch {
            // Barretenberg may throw on invalid proof format -- this is acceptable
            expect(true).toBe(true);
        }
    }, 60_000);

    // ========================================================================
    // Test 7: verifyProofWithExpectedInputs works with keccak
    // ========================================================================

    it('verifyProofWithExpectedInputs works with keccak proof', async () => {
        const valid = await prover.verifyProofWithExpectedInputs(
            keccakProof,
            validInputs,
            { keccak: true },
        );
        expect(valid).toBe(true);
    }, 60_000);

    // ========================================================================
    // Test 8: verifyProofWithExpectedInputs works with default proof
    // ========================================================================

    it('verifyProofWithExpectedInputs works with default proof', async () => {
        const valid = await prover.verifyProofWithExpectedInputs(
            defaultProof,
            validInputs,
        );
        expect(valid).toBe(true);
    }, 60_000);

    // ========================================================================
    // Test 9: Proof bytes differ between modes (not just size)
    // ========================================================================

    it('proof bytes differ between keccak and default modes', () => {
        // The raw proof bytes must be different (different hash functions used internally)
        const minLen = Math.min(keccakProof.proof.length, defaultProof.proof.length);
        let identical = true;
        for (let i = 0; i < minLen; i++) {
            if (keccakProof.proof[i] !== defaultProof.proof[i]) {
                identical = false;
                break;
            }
        }
        expect(identical).toBe(false);
    });
});
