// Auto-generated registry entries
// Copy into known-portals.ts KNOWN_PORTALS object

  '0477000': {
    cityFips: '0477000',
    cityName: 'Tucson',
    state: 'AZ',
    portalType: 'arcgis',
    downloadUrl: 'https://services3.arcgis.com/9coHY2fvuFjG9HQX/arcgis/rest/services/Section_8_Housing_per_Ward/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 6,
    lastVerified: '2025-11-23T11:37:56.839372Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'section 8 housing per ward' by lsharp1_cotgis (6 features); Validation: Passed (6 features, bounds OK)',
  },

  '0446000': {
    cityFips: '0446000',
    cityName: 'Mesa',
    state: 'AZ',
    portalType: 'arcgis',
    downloadUrl: 'https://services2.arcgis.com/1gVyYKfYgW5Nxb1V/arcgis/rest/services/CouncilDistrict/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 6,
    lastVerified: '2025-11-23T11:37:56.839915Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'councildistrict' by mesaaz (6 features); Validation: Passed (6 features, bounds OK)',
  },

  '0427820': {
    cityFips: '0427820',
    cityName: 'Glendale',
    state: 'AZ',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/ykpntM6e3tHvzKRJ/arcgis/rest/services/Maricopa_County_City_Council_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 6,
    lastVerified: '2025-11-23T11:37:59.597275Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'maricopa county city council districts' by maricopaelectionsgis (38 features); Filtered county data: 6 features for Glendal',
  },

  '0454050': {
    cityFips: '0454050',
    cityName: 'Peoria',
    state: 'AZ',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/ykpntM6e3tHvzKRJ/arcgis/rest/services/Maricopa_County_City_Council_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 6,
    lastVerified: '2025-11-23T11:38:31.234113Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'maricopa county city council districts' by maricopaelectionsgis (38 features); Filtered county data: 6 features for Peoria;',
  },

  '0471510': {
    cityFips: '0471510',
    cityName: 'Surprise',
    state: 'AZ',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/ykpntM6e3tHvzKRJ/arcgis/rest/services/Maricopa_County_City_Council_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 6,
    lastVerified: '2025-11-23T11:39:11.698373Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'maricopa county city council districts' by maricopaelectionsgis (38 features); Filtered county data: 6 features for Surpris',
  },

  '0407940': {
    cityFips: '0407940',
    cityName: 'Buckeye',
    state: 'AZ',
    portalType: 'arcgis',
    downloadUrl: 'https://maps.buckeyeaz.gov/server/rest/services/Boundaries/Buckeye_City_Voting_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 6,
    lastVerified: '2025-11-23T11:40:36.801871Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'buckeye city voting districts' by cityofbuckeye (6 features); Validation: Passed (6 features, bounds OK)',
  },

  '0423760': {
    cityFips: '0423760',
    cityName: 'Florence',
    state: 'AZ',
    portalType: 'arcgis',
    downloadUrl: 'https://services1.arcgis.com/40L6yX6OtdCifNez/arcgis/rest/services/Municipal_Council_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 3,
    lastVerified: '2025-11-23T11:43:40.257144Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'municipal council districts' by ebenston_florencesc (3 features); Validation: Passed (3 features, bounds OK)',
  },

