// Auto-generated registry entries
// Copy into known-portals.ts KNOWN_PORTALS object

  '4845000': {
    cityFips: '4845000',
    cityName: 'Lubbock',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services2.arcgis.com/eYXun6c1pgy8Qpta/arcgis/rest/services/Council_District_Outlines/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 6,
    lastVerified: '2025-11-23T10:44:50.557378Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'council district outlines' by gisds_cityoflubbock (6 features); Validation: Passed (6 features, bounds OK)',
  },

  '4839148': {
    cityFips: '4839148',
    cityName: 'Killeen',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services6.arcgis.com/1UWmeVkkResmC9lR/arcgis/rest/services/Killeen_Council_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 4,
    lastVerified: '2025-11-23T10:46:07.399167Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'killeen_council_districts' by a-sanchez (4 features); Validation: Passed (4 features, bounds OK)',
  },

  '4856000': {
    cityFips: '4856000',
    cityName: 'Pasadena',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services2.arcgis.com/zNjnZafDYCAJAbN0/arcgis/rest/services/City_Council_Districts_view/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 7,
    lastVerified: '2025-11-23T10:46:07.399313Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'city council districts' by cityofpasadenacagis (7 features); Validation: Passed (7 features, bounds OK)',
  },

  '4876000': {
    cityFips: '4876000',
    cityName: 'Waco',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://gis.wacotx.gov/server/rest/services/Council_District_Waco_Map/FeatureServer/86/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 5,
    lastVerified: '2025-11-23T10:46:22.299341Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via gemini_grounded. Reasoning: Registry miss; ArcGIS API: No matching data found; Gemini: Testing ArcGIS candidate https://hub.arcgis.com/datasets/wacogis::council-district-map/explor',
  },

  '4874144': {
    cityFips: '4874144',
    cityName: 'Tyler',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services5.arcgis.com/RmXXW3PwBZGOxlSe/arcgis/rest/services/Council_Districts_Tyler/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 6,
    lastVerified: '2025-11-23T10:48:59.658361Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'council districts - tyler' by ldowney_gis (6 features); Validation: Passed (6 features, bounds OK)',
  },

  '4848768': {
    cityFips: '4848768',
    cityName: 'Mission',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/GL0fWlNkwysZaKeV/arcgis/rest/services/FY2021_Birth_to_Five_Councils/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 39,
    lastVerified: '2025-11-23T10:50:00.237893Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'fy2021 birth to five councils' by lnleonar@illinois.edu_univofillinois_1190444167 (39 features); Validation: Passed (39 fea',
  },

  '4806128': {
    cityFips: '4806128',
    cityName: 'Baytown',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services8.arcgis.com/2iaYWEMdQLPv0ZUw/arcgis/rest/services/2022_Council_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 6,
    lastVerified: '2025-11-23T10:50:19.740690Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found '2022_council_districts' by lianette.leon (6 features); Validation: Passed (6 features, bounds OK)',
  },

  '4872176': {
    cityFips: '4872176',
    cityName: 'Temple',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services3.arcgis.com/jjDKBbyoUNyhuTYf/arcgis/rest/services/Intersect_of_Temple_City_Council_Districts_2020_and_Temple_City_Council_Districts_2022_final/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 34,
    lastVerified: '2025-11-23T10:50:19.740846Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'intersect_of_temple_city_council_districts_2020_and_temple_city_council_districts_2022_final' by molinarr (34 features); Va',
  },

  '4843888': {
    cityFips: '4843888',
    cityName: 'Longview',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services2.arcgis.com/L4ywDaHbEfVZyfpl/arcgis/rest/services/Council_District_20211110/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 6,
    lastVerified: '2025-11-23T10:50:19.740918Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'council_district_20211110' by stremmel_longviewtexas (6 features); Validation: Passed (6 features, bounds OK)',
  },

  '4848804': {
    cityFips: '4848804',
    cityName: 'Missouri City',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services2.arcgis.com/6vRbgYSxztFGZwla/arcgis/rest/services/Missouri_City_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 4,
    lastVerified: '2025-11-23T10:51:03.682157Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'missouri city districts' by jian@missouricity (4 features); Validation: Passed (4 features, bounds OK)',
  },

  '4852356': {
    cityFips: '4852356',
    cityName: 'North Richland Hills',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services6.arcgis.com/ikurHvtarxfN6u3u/arcgis/rest/services/FireDistricts_All/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 10,
    lastVerified: '2025-11-23T10:51:15.765075Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'fire districts' by gis_valley_county_2016 (10 features); Validation: Passed (10 features, bounds OK)',
  },

  '4829336': {
    cityFips: '4829336',
    cityName: 'Georgetown',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/EAoy39bcmpweKJ4f/arcgis/rest/services/Georgetown_Voter_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 3,
    lastVerified: '2025-11-23T10:51:15.765320Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'georgetown voter districts' by cmoore92 (3 features); Validation: Passed (3 features, bounds OK)',
  },

  '4875428': {
    cityFips: '4875428',
    cityName: 'Victoria',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services6.arcgis.com/z8Duli34FfmN3nn5/arcgis/rest/services/City_of_Victoria_Council_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 4,
    lastVerified: '2025-11-23T10:51:17.205539Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'city of victoria council districts' by covgis (4 features); Validation: Passed (4 features, bounds OK)',
  },

  '4872530': {
    cityFips: '4872530',
    cityName: 'The Colony',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services1.arcgis.com/Mg7DLdfYcSWIaDnu/arcgis/rest/services/Proposed_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 12,
    lastVerified: '2025-11-23T10:53:19.672736Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'proposed districts' by gis_lfucg (12 features); Validation: Passed (12 features, bounds OK)',
  },

  '4821628': {
    cityFips: '4821628',
    cityName: 'Duncanville',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services3.arcgis.com/mjqW4t1A3YDrjss0/arcgis/rest/services/Duncanville_Council_Districts_2021_WFL1/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 5,
    lastVerified: '2025-11-23T10:53:23.484515Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'duncanville council districts 2021_wfl1' by dunawayduncanville (5 features); Validation: Passed (5 features, bounds OK)',
  },

  '4825452': {
    cityFips: '4825452',
    cityName: 'Farmers Branch',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services1.arcgis.com/rrMt0tlqg3eYOL0M/arcgis/rest/services/Council_Districts_public/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 5,
    lastVerified: '2025-11-23T10:53:25.799848Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'council districts_public' by cityoffarmersbranchtx (5 features); Validation: Passed (5 features, bounds OK)',
  },

  '4865516': {
    cityFips: '4865516',
    cityName: 'San Juan',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/PNkCg7xWnaf90qde/arcgis/rest/services/Residency_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 3,
    lastVerified: '2025-11-23T10:53:25.800047Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'residency districts' by sjcgis_sjcgis (3 features); Validation: Passed (3 features, bounds OK)',
  },

  '4814920': {
    cityFips: '4814920',
    cityName: 'Cibolo',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services3.arcgis.com/D32JCd9p0r1BYMwd/arcgis/rest/services/CouncilDistricts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 7,
    lastVerified: '2025-11-23T10:53:29.083078Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'city of cibolo single member districts (old)' by cocgisonline (7 features); Validation: Passed (7 features, bounds OK)',
  },

  '4859696': {
    cityFips: '4859696',
    cityName: 'Prosper',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services2.arcgis.com/zNjnZafDYCAJAbN0/arcgis/rest/services/2001_City_Council_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 7,
    lastVerified: '2025-11-23T10:53:30.062801Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found '2001 city council districts' by cityofpasadenacagis (7 features); Validation: Passed (7 features, bounds OK)',
  },

  '4866644': {
    cityFips: '4866644',
    cityName: 'Seguin',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://gis.seguintexas.gov/arcgis/rest/services/Data_Download/Council_Districts_Open_Data/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 8,
    lastVerified: '2025-11-23T10:53:30.881861Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'council districts open data (seguin, texas)' by gis@seguintexas.gov (8 features); Validation: Passed (8 features, bounds OK',
  },

  '4830920': {
    cityFips: '4830920',
    cityName: 'Greenville',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/EAoy39bcmpweKJ4f/arcgis/rest/services/Greenville_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 3,
    lastVerified: '2025-11-23T10:53:30.882318Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'greenville districts' by cmoore92 (3 features); Validation: Passed (3 features, bounds OK)',
  },

