// Auto-generated registry entries
// Copy into known-portals.ts KNOWN_PORTALS object

  '4845000': {
    cityFips: '4845000',
    cityName: 'Lubbock',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services2.arcgis.com/eYXun6c1pgy8Qpta/arcgis/rest/services/Council_District_Outlines/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 6,
    lastVerified: '2025-11-23T10:38:24.991566Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'council district outlines' by gisds_cityoflubbock (6 features); Validation: Passed (6 features)',
  },

  '4839148': {
    cityFips: '4839148',
    cityName: 'Killeen',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services6.arcgis.com/1UWmeVkkResmC9lR/arcgis/rest/services/Killeen_Council_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 4,
    lastVerified: '2025-11-23T10:39:15.565303Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'killeen_council_districts' by a-sanchez (4 features); Validation: Passed (4 features)',
  },

  '4856000': {
    cityFips: '4856000',
    cityName: 'Pasadena',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services2.arcgis.com/zNjnZafDYCAJAbN0/arcgis/rest/services/City_Council_Districts_view/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 7,
    lastVerified: '2025-11-23T10:39:15.565450Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'city council districts' by cityofpasadenacagis (7 features); Validation: Passed (7 features)',
  },

  '4863500': {
    cityFips: '4863500',
    cityName: 'Round Rock',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/njFNhDsUCentVYJW/arcgis/rest/services/MDOT_SHA_District_Boundaries/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 7,
    lastVerified: '2025-11-23T10:40:15.644990Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'mdot sha district boundaries' by mdotsha.gis (7 features); Validation: Passed (7 features)',
  },

  '4874144': {
    cityFips: '4874144',
    cityName: 'Tyler',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services5.arcgis.com/RmXXW3PwBZGOxlSe/arcgis/rest/services/Council_Districts_Tyler/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 6,
    lastVerified: '2025-11-23T10:40:38.644451Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'council districts - tyler' by ldowney_gis (6 features); Validation: Passed (6 features)',
  },

  '4864472': {
    cityFips: '4864472',
    cityName: 'San Angelo',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/njFNhDsUCentVYJW/arcgis/rest/services/MDOT_SHA_District_Boundaries/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 7,
    lastVerified: '2025-11-23T10:40:51.411363Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'mdot sha district boundaries' by mdotsha.gis (7 features); Validation: Passed (7 features)',
  },

  '4850820': {
    cityFips: '4850820',
    cityName: 'New Braunfels',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/XTtANUDT8Va4DLwI/arcgis/rest/services/NZ_District_Health_Board_boundaries/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 20,
    lastVerified: '2025-11-23T10:40:51.411431Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'nz district health board boundaries - generalised' by eaglegis (20 features); Validation: Passed (20 features)',
  },

  '4848768': {
    cityFips: '4848768',
    cityName: 'Mission',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/GL0fWlNkwysZaKeV/arcgis/rest/services/FY2021_Birth_to_Five_Councils/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 39,
    lastVerified: '2025-11-23T10:41:03.417455Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'fy2021 birth to five councils' by lnleonar@illinois.edu_univofillinois_1190444167 (39 features); Validation: Passed (39 fea',
  },

  '4806128': {
    cityFips: '4806128',
    cityName: 'Baytown',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services8.arcgis.com/2iaYWEMdQLPv0ZUw/arcgis/rest/services/2022_Council_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 6,
    lastVerified: '2025-11-23T10:41:12.658662Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found '2022_council_districts' by lianette.leon (6 features); Validation: Passed (6 features)',
  },

  '4872176': {
    cityFips: '4872176',
    cityName: 'Temple',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services3.arcgis.com/jjDKBbyoUNyhuTYf/arcgis/rest/services/Intersect_of_Temple_City_Council_Districts_2020_and_Temple_City_Council_Districts_2022_final/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 34,
    lastVerified: '2025-11-23T10:41:12.658878Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'intersect_of_temple_city_council_districts_2020_and_temple_city_council_districts_2022_final' by molinarr (34 features); Va',
  },

  '4843888': {
    cityFips: '4843888',
    cityName: 'Longview',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services2.arcgis.com/L4ywDaHbEfVZyfpl/arcgis/rest/services/Council_District_20211110/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 6,
    lastVerified: '2025-11-23T10:41:12.658941Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'council_district_20211110' by stremmel_longviewtexas (6 features); Validation: Passed (6 features)',
  },

  '4848804': {
    cityFips: '4848804',
    cityName: 'Missouri City',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services2.arcgis.com/6vRbgYSxztFGZwla/arcgis/rest/services/Missouri_City_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 4,
    lastVerified: '2025-11-23T10:41:32.950505Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'missouri city districts' by jian@missouricity (4 features); Validation: Passed (4 features)',
  },

  '4852356': {
    cityFips: '4852356',
    cityName: 'North Richland Hills',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services6.arcgis.com/ikurHvtarxfN6u3u/arcgis/rest/services/FireDistricts_All/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 10,
    lastVerified: '2025-11-23T10:41:40.875330Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'fire districts' by gis_valley_county_2016 (10 features); Validation: Passed (10 features)',
  },

  '4829336': {
    cityFips: '4829336',
    cityName: 'Georgetown',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/EAoy39bcmpweKJ4f/arcgis/rest/services/Georgetown_Voter_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 3,
    lastVerified: '2025-11-23T10:41:40.875608Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'georgetown voter districts' by cmoore92 (3 features); Validation: Passed (3 features)',
  },

  '4875428': {
    cityFips: '4875428',
    cityName: 'Victoria',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services6.arcgis.com/z8Duli34FfmN3nn5/arcgis/rest/services/City_of_Victoria_Council_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 4,
    lastVerified: '2025-11-23T10:41:42.769235Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'city of victoria council districts' by covgis (4 features); Validation: Passed (4 features)',
  },

  '4858820': {
    cityFips: '4858820',
    cityName: 'Port Arthur',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services1.arcgis.com/kFBW8xGuknyS8WK0/arcgis/rest/services/Official_Redistricting_Lines_for_Port_Arthur_/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 4,
    lastVerified: '2025-11-23T10:42:09.451388Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'official redistricting lines for port arthur ' by copa409 (4 features); Validation: Passed (4 features)',
  },

  '4872392': {
    cityFips: '4872392',
    cityName: 'Texas City',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/KTcxiTD9dsQw4r7Z/arcgis/rest/services/Texas_State_Senate_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 31,
    lastVerified: '2025-11-23T10:42:32.275745Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'texas state senate districts' by tpp_gis (31 features); Validation: Passed (31 features)',
  },

  '4872530': {
    cityFips: '4872530',
    cityName: 'The Colony',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services1.arcgis.com/Mg7DLdfYcSWIaDnu/arcgis/rest/services/Proposed_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 12,
    lastVerified: '2025-11-23T10:42:44.495115Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'proposed districts' by gis_lfucg (12 features); Validation: Passed (12 features)',
  },

  '4867496': {
    cityFips: '4867496',
    cityName: 'Sherman',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services7.arcgis.com/iMHDvyzuG2Q2tuit/arcgis/rest/services/Council_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 7,
    lastVerified: '2025-11-23T10:42:45.808378Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'council districts' by shermangis7 (7 features); Validation: Passed (7 features)',
  },

  '4821628': {
    cityFips: '4821628',
    cityName: 'Duncanville',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services3.arcgis.com/mjqW4t1A3YDrjss0/arcgis/rest/services/Duncanville_Council_Districts_2021_WFL1/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 5,
    lastVerified: '2025-11-23T10:42:48.611369Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'duncanville council districts 2021_wfl1' by dunawayduncanville (5 features); Validation: Passed (5 features)',
  },

  '4825452': {
    cityFips: '4825452',
    cityName: 'Farmers Branch',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services1.arcgis.com/rrMt0tlqg3eYOL0M/arcgis/rest/services/Council_Districts_public/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 5,
    lastVerified: '2025-11-23T10:42:51.382670Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'council districts_public' by cityoffarmersbranchtx (5 features); Validation: Passed (5 features)',
  },

  '4865516': {
    cityFips: '4865516',
    cityName: 'San Juan',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/PNkCg7xWnaf90qde/arcgis/rest/services/Residency_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 3,
    lastVerified: '2025-11-23T10:42:51.382803Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'residency districts' by sjcgis_sjcgis (3 features); Validation: Passed (3 features)',
  },

  '4841440': {
    cityFips: '4841440',
    cityName: 'La Porte',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/njFNhDsUCentVYJW/arcgis/rest/services/MDOT_SHA_District_Boundaries/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 7,
    lastVerified: '2025-11-23T10:42:52.521001Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'mdot sha district boundaries' by mdotsha.gis (7 features); Validation: Passed (7 features)',
  },

  '4814920': {
    cityFips: '4814920',
    cityName: 'Cibolo',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services3.arcgis.com/D32JCd9p0r1BYMwd/arcgis/rest/services/CouncilDistricts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 7,
    lastVerified: '2025-11-23T10:42:55.068044Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'city of cibolo single member districts (old)' by cocgisonline (7 features); Validation: Passed (7 features)',
  },

  '4859696': {
    cityFips: '4859696',
    cityName: 'Prosper',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services2.arcgis.com/zNjnZafDYCAJAbN0/arcgis/rest/services/2001_City_Council_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 7,
    lastVerified: '2025-11-23T10:42:56.170592Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found '2001 city council districts' by cityofpasadenacagis (7 features); Validation: Passed (7 features)',
  },

  '4866644': {
    cityFips: '4866644',
    cityName: 'Seguin',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://gis.seguintexas.gov/arcgis/rest/services/Data_Download/Council_Districts_Open_Data/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 8,
    lastVerified: '2025-11-23T10:42:57.299202Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'council districts open data (seguin, texas)' by gis@seguintexas.gov (8 features); Validation: Passed (8 features)',
  },

  '4830920': {
    cityFips: '4830920',
    cityName: 'Greenville',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/EAoy39bcmpweKJ4f/arcgis/rest/services/Greenville_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 3,
    lastVerified: '2025-11-23T10:42:57.299413Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'greenville districts' by cmoore92 (3 features); Validation: Passed (3 features)',
  },

  '4821892': {
    cityFips: '4821892',
    cityName: 'Eagle Pass',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/XTtANUDT8Va4DLwI/arcgis/rest/services/NZ_District_Health_Board_boundaries/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 20,
    lastVerified: '2025-11-23T10:42:58.410825Z',
    confidence: 80,
    discoveredBy: 'automated',
    notes: 'Batch discovery via arcgis_api. Reasoning: Registry miss; ArcGIS API: Found 'nz district health board boundaries - generalised' by eaglegis (20 features); Validation: Passed (20 features)',
  },

