import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { writeChunkedOutputs } from '../../../../scripts/build-chunked-mapping.js';
import {
  mergeAddressIndexIntoManifest,
  type AddressIndexManifestFields,
} from '../../../distribution/addresses/chunk-emit.js';
import { resolveNadVintage } from '../../../distribution/addresses/nad-vintage.js';
import { resolveTigerVintage } from '../../../distribution/snapshots/tiger-vintage.js';

/**
 * SEAM-CONTRACT v1 §4: `addressIndexGenerated` is a THIRD manifest clock,
 * distinct from `generated` (boundary) and `officialsGenerated` (officials).
 * The address publish MERGES into the existing US/manifest.json and must
 * leave every pre-existing field byte-unchanged — never collapsed, never
 * borrowed. The boundary manifest here is produced by the REAL boundary
 * writer (writeChunkedOutputs), not a mock.
 */
describe('addressIndex manifest merge (§4 third clock)', () => {
  let outDir: string;

  const CELL = '872830828ffffff';
  const PARENT_RES3 = '832830fffffffff';
  const mapping = { [CELL]: ['CA-12', null] as (string | null)[] };
  const chunkGroups = new Map<string, Record<string, (string | null)[]>>([
    [PARENT_RES3, { [CELL]: mapping[CELL] }],
  ]);
  const slotNames = { 0: 'us_house', 1: 'us_senate' };
  const stats = {
    totalEnumerated: 1,
    oceanFiltered: 0,
    totalProcessed: 1,
    totalMatched: 1,
    totalNoCandidate: 0,
    totalCacheHits: 0,
    totalCacheMisses: 0,
    workerCount: 1,
    totalElapsedSec: 1,
  };

  const OFFICIALS_GENERATED = '2026-06-15T04:00:00.000Z';

  function addressFields(): AddressIndexManifestFields {
    return {
      addressIndexGenerated: new Date().toISOString(),
      addressIndexVersion: 1,
      addressIndex: {
        schemaVersion: 1,
        normVersion: 1,
        normTable: { path: 'addresses/normalization.json', sha256: 'a'.repeat(64), bytes: 12345 },
        nadVintage: resolveNadVintage('2026-06-30', { dryRun: false }),
        addrfeatVintage: resolveTigerVintage('TIGER2025', { dryRun: false }),
        totalChunks: 42,
        totalStreets: 1000,
        totalPoints: 5000,
        totalRanges: 7000,
        chunkIndex: { path: 'addresses/chunk-index.json', sha256: 'b'.repeat(64), bytes: 999 },
        sourceMix: { DE: { nadPoints: 0, tigerRanges: 7000 } },
      },
    };
  }

  beforeEach(() => {
    outDir = mkdtempSync(join(tmpdir(), 'manifest-merge-'));
    // Produce the REAL boundary manifest the address build merges into.
    writeChunkedOutputs(
      outDir,
      mapping,
      chunkGroups,
      slotNames,
      'TIGER2025',
      OFFICIALS_GENERATED,
      stats
    );
  });

  afterEach(() => {
    rmSync(outDir, { recursive: true, force: true });
  });

  /** The raw serialized line for a top-level key, e.g. `  "generated": "…",`. */
  function rawLineFor(manifestRaw: string, key: string): string {
    const match = manifestRaw
      .split('\n')
      .filter((line) => line.trimStart().startsWith(`"${key}":`));
    expect(match, `expected exactly one top-level "${key}" line`).toHaveLength(1);
    return match[0].replace(/,\s*$/, '');
  }

  it('leaves generated / tigerVintage / officialsGenerated BYTE-identical through the merge', () => {
    const manifestPath = join(outDir, 'US', 'manifest.json');
    const before = readFileSync(manifestPath, 'utf-8');
    const beforeLines = {
      generated: rawLineFor(before, 'generated'),
      tigerVintage: rawLineFor(before, 'tigerVintage'),
      officialsGenerated: rawLineFor(before, 'officialsGenerated'),
    };

    mergeAddressIndexIntoManifest(outDir, addressFields());

    const after = readFileSync(manifestPath, 'utf-8');
    expect(rawLineFor(after, 'generated')).toBe(beforeLines.generated);
    expect(rawLineFor(after, 'tigerVintage')).toBe(beforeLines.tigerVintage);
    expect(rawLineFor(after, 'officialsGenerated')).toBe(beforeLines.officialsGenerated);

    // Every pre-existing field survives with identical values (deep).
    const beforeObj = JSON.parse(before) as Record<string, unknown>;
    const afterObj = JSON.parse(after) as Record<string, unknown>;
    for (const key of Object.keys(beforeObj)) {
      expect(afterObj[key]).toEqual(beforeObj[key]);
    }
  });

  it('adds the third clock without borrowing either existing clock', () => {
    mergeAddressIndexIntoManifest(outDir, addressFields());
    const manifest = JSON.parse(
      readFileSync(join(outDir, 'US', 'manifest.json'), 'utf-8')
    ) as Record<string, unknown>;

    expect(typeof manifest.addressIndexGenerated).toBe('string');
    // Parses as ISO-8601.
    expect(
      Number.isNaN(Date.parse(manifest.addressIndexGenerated as string))
    ).toBe(false);
    // Third clock ≠ boundary clock, third clock ≠ officials clock: the merge
    // never collapses or borrows (the values were produced independently).
    expect(manifest.addressIndexGenerated).not.toBe(manifest.generated);
    expect(manifest.addressIndexGenerated).not.toBe(manifest.officialsGenerated);
    expect(manifest.addressIndexVersion).toBe(1);

    const idx = manifest.addressIndex as Record<string, unknown>;
    expect(idx.schemaVersion).toBe(1);
    expect(idx.normVersion).toBe(1);
    expect(idx.nadVintage).toBe('2026-06-30');
    expect(idx.addrfeatVintage).toBe('TIGER2025');
    expect(idx.normTable).toMatchObject({ path: 'addresses/normalization.json' });
    expect(idx.chunkIndex).toMatchObject({ path: 'addresses/chunk-index.json' });
  });

  it("vintage gates are fail-loud: 'unknown' (the parse-arg default) can never reach a produced manifest", () => {
    // Both gates THROW on a real (non-dry) run before anything is written…
    expect(() => resolveNadVintage('unknown', { dryRun: false })).toThrow(/ISO date/);
    expect(() => resolveTigerVintage('unknown', { dryRun: false })).toThrow(/TIGER20YY/);
    expect(() => resolveNadVintage('', { dryRun: false })).toThrow(/ISO date/);
    expect(() => resolveNadVintage('2026-13-99', { dryRun: false })).toThrow(/ISO date/);
    expect(() => resolveNadVintage('20260630', { dryRun: false })).toThrow(/ISO date/);

    // …while a dry run previews the raw label without failing.
    expect(resolveNadVintage('unknown', { dryRun: true })).toBe('unknown');
    expect(resolveTigerVintage('unknown', { dryRun: true })).toBe('unknown');

    // And a manifest produced through the real merge path never carries it.
    mergeAddressIndexIntoManifest(outDir, addressFields());
    const raw = readFileSync(join(outDir, 'US', 'manifest.json'), 'utf-8');
    expect(raw).not.toContain('"nadVintage": "unknown"');
    expect(raw).not.toContain('"addrfeatVintage": "unknown"');
  });

  it('valid vintages pass their gates unchanged', () => {
    expect(resolveNadVintage('2026-06-30', { dryRun: false })).toBe('2026-06-30');
    expect(resolveTigerVintage('TIGER2025', { dryRun: false })).toBe('TIGER2025');
  });

  it('creates a minimal manifest shell when none exists (sample builds), fabricating NO clocks', () => {
    const freshDir = mkdtempSync(join(tmpdir(), 'manifest-merge-fresh-'));
    try {
      expect(existsSync(join(freshDir, 'US', 'manifest.json'))).toBe(false);
      mergeAddressIndexIntoManifest(freshDir, addressFields());
      const manifest = JSON.parse(
        readFileSync(join(freshDir, 'US', 'manifest.json'), 'utf-8')
      ) as Record<string, unknown>;
      expect(manifest.addressIndexVersion).toBe(1);
      // Boundary/officials clocks are ABSENT — honestly unknown, never
      // fabricated from the address clock (consumer degrades to null).
      expect('generated' in manifest).toBe(false);
      expect('tigerVintage' in manifest).toBe(false);
      expect('officialsGenerated' in manifest).toBe(false);
    } finally {
      rmSync(freshDir, { recursive: true, force: true });
    }
  });
});
