action_domain = ""
authority_level = ""
cell_id = ""
cell_map_path = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
cell_map_path_bits = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
cell_map_root = ""
districts = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
nullifier = ""
registration_salt = ""
user_index = ""
user_path = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
user_root = ""
user_secret = ""
