// SPDX-License-Identifier: MIT
pragma solidity =0.8.19;

import "forge-std/Script.sol";

/**
 * @title Deploy Halo2Verifier
 * @notice Deploys the Halo2Verifier contract from pre-generated bytecode
 * @dev Bytecode is generated from the circuit using halo2-solidity
 */
contract DeployHalo2Verifier is Script {
    function run() external {
        // Read deployment bytecode from file
        string memory bytecodeFile = "src/Halo2Verifier.bytecode";
        bytes memory bytecode = vm.readFileBinary(bytecodeFile);

        console.log("Deploying Halo2Verifier...");
        console.log("Bytecode size:", bytecode.length, "bytes");
        console.log("EIP-170 limit: 24576 bytes");
        console.log("Margin:", 24576 - bytecode.length, "bytes");

        require(bytecode.length <= 24576, "Bytecode exceeds EIP-170 limit");

        // Get deployer private key from environment
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");

        // Start broadcast
        vm.startBroadcast(deployerPrivateKey);

        // Deploy contract using bytecode
        address verifier;
        assembly {
            verifier := create(0, add(bytecode, 0x20), mload(bytecode))
        }

        require(verifier != address(0), "Deployment failed");

        vm.stopBroadcast();

        console.log("==========================================");
        console.log("Halo2Verifier deployed at:", verifier);
        console.log("==========================================");
        console.log("");
        console.log("Next steps:");
        console.log("1. Verify contract on Scrollscan:");
        console.log("   forge verify-contract", verifier, "Halo2Verifier --chain scroll-sepolia");
        console.log("2. Deploy DistrictRegistry");
        console.log("3. Deploy DistrictGate with verifier address");
        console.log("==========================================");
    }
}
