/**
 * Generate Solidity HonkVerifier from @aztec/bb.js
 *
 * This ensures the Solidity verifier is compatible with proofs
 * generated by the same version of bb.js (v2.1.8).
 *
 * Usage:
 *   npx tsx scripts/generate-verifier-sol.ts [--depth 20]
 */

import { UltraHonkBackend } from '@aztec/bb.js';
import type { CompiledCircuit } from '@noir-lang/noir_js';
import { writeFileSync } from 'fs';
import { resolve } from 'path';

const REPO_ROOT = resolve(new URL('.', import.meta.url).pathname, '..');
const DEPTHS = [18, 20, 22, 24] as const;

// Parse args
const depthArg = process.argv.includes('--depth')
  ? Number(process.argv[process.argv.indexOf('--depth') + 1])
  : null;
const depths = depthArg ? [depthArg] : [...DEPTHS];

async function generateVerifier(depth: number): Promise<string> {
  console.log(`\n[${depth}] Loading circuit...`);
  const circuitPath = resolve(
    REPO_ROOT,
    `packages/noir-prover/circuits/two_tree_membership_${depth}.json`,
  );
  const module = await import(circuitPath);
  const circuit = module.default as unknown as CompiledCircuit;

  console.log(`[${depth}] Creating UltraHonkBackend...`);
  const backend = new UltraHonkBackend(circuit.bytecode, { threads: 1 });

  console.log(`[${depth}] Generating Solidity verifier (this may take a moment)...`);
  const soliditySource = await backend.getSolidityVerifier();

  await backend.destroy();

  return soliditySource;
}

async function main() {
  console.log('=== Solidity Verifier Generation (bb.js) ===');
  console.log(`Depths: ${depths.join(', ')}`);

  for (const depth of depths) {
    const source = await generateVerifier(depth);

    // Rename the contract from HonkVerifier to HonkVerifier_{depth}
    const renamed = source.replace(
      /contract HonkVerifier is/g,
      `contract HonkVerifier_${depth} is`,
    );

    const outPath = resolve(
      REPO_ROOT,
      `contracts/src/verifiers/HonkVerifier_${depth}.sol`,
    );
    writeFileSync(outPath, renamed);
    console.log(`[${depth}] Written to: ${outPath}`);
    console.log(`[${depth}] Size: ${renamed.length} chars`);
  }

  console.log('\n=== Done ===');
}

main().catch((err) => {
  console.error('FATAL:', err);
  process.exit(1);
});
