/**
 * Single-Feature Quarantine Data
 *
 * Extracted entries from known-portals.ts with only 1 feature
 * These cannot represent valid council district tessellations
 *
 * Generated: 2026-01-16
 */

import type { QuarantinedPortal } from './quarantined-portals.js';

export const SINGLE_FEATURE_ENTRIES: Record<string, QuarantinedPortal> = {
  '20177': {
    cityFips: '20177',
    cityName: 'Shawnee County',
    state: 'KS',
    portalType: 'arcgis',
    downloadUrl: 'https://services1.arcgis.com/EvtgI3PZ9PyCGJZS/arcgis/rest/services/lrolph64_488e22218cfe4eef_CD7_layers/FeatureServer/7/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 58,
    discoveredBy: 'automated',
    notes: 'Shawnee County KS - 1 districts, bulk ingested from "Council District"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '40031': {
    cityFips: '40031',
    cityName: 'Comanche County',
    state: 'OK',
    portalType: 'arcgis',
    downloadUrl: 'https://services2.arcgis.com/baoUryRiOxhCY0yb/arcgis/rest/services/Lawton_Admin_Boundaries/FeatureServer/3/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 50,
    discoveredBy: 'automated',
    notes: 'Comanche County OK - 1 districts, bulk ingested from "Lawton City Ward Boundaries Outside Area"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '40109': {
    cityFips: '40109',
    cityName: 'Oklahoma County',
    state: 'OK',
    portalType: 'arcgis',
    downloadUrl: 'https://services7.arcgis.com/OJ8CIjB2a1JPYuG7/arcgis/rest/services/Piedmont_Base_Map/FeatureServer/9/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 50,
    discoveredBy: 'automated',
    notes: 'Oklahoma County OK - 1 districts, bulk ingested from "City_Wards_2023_City_of_Piedmont_Mask"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '42091': {
    cityFips: '42091',
    cityName: 'Montgomery County',
    state: 'PA',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/fLeGjb7u4uXqeF9q/arcgis/rest/services/4th_Council_District_Part_1_Crimes_in_2021_WFL1/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 50,
    discoveredBy: 'automated',
    notes: 'Montgomery County PA - 1 districts, bulk ingested from "Council District Boundary"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '48029': {
    cityFips: '48029',
    cityName: 'Bexar County',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services6.arcgis.com/BAJNi3EgCdtQ1BCG/arcgis/rest/services/Council_District_6/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 50,
    discoveredBy: 'automated',
    notes: 'Bexar County TX - 1 districts, bulk ingested from "Council_District_6"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '2247560': {
    cityFips: '2247560',
    cityName: 'Madisonville',
    state: 'LA',
    portalType: 'arcgis',
    downloadUrl: 'https://services8.arcgis.com/xqfvcYWRsxGrAkQR/arcgis/rest/services/Council_District_4_WFL1/FeatureServer/3/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 55,
    discoveredBy: 'automated',
    notes: 'Madisonville LA - 1 districts, bulk ingested from "Council District 4"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '3774440': {
    cityFips: '3774440',
    cityName: 'Wilmington',
    state: 'NC',
    portalType: 'arcgis',
    downloadUrl: 'https://services1.arcgis.com/KHqZAAIdlp1670Ft/arcgis/rest/services/ElectoralDistricts/FeatureServer/2/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 55,
    discoveredBy: 'automated',
    notes: 'Wilmington NC - 1 districts, bulk ingested from "City Council"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '3957750': {
    cityFips: '3957750',
    cityName: 'Oakwood',
    state: 'OH',
    portalType: 'arcgis',
    downloadUrl: 'https://services5.arcgis.com/Xti6g2pFdrO8EjbP/arcgis/rest/services/DNA_Rising___20240220_WFL1/FeatureServer/1/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 55,
    discoveredBy: 'automated',
    notes: 'Oakwood OH - 1 districts, bulk ingested from "Cuyahoga Council District 9"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '4806128': {
    cityFips: '4806128',
    cityName: 'Baytown',
    state: 'TX',
    portalType: 'arcgis',
    downloadUrl: 'https://services8.arcgis.com/2iaYWEMdQLPv0ZUw/arcgis/rest/services/Find_Locations_in_2022_Council_Districts/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 63,
    discoveredBy: 'automated',
    notes: 'Baytown TX - 1 districts, bulk ingested from "Find_Locations_in_2022_Council_Districts"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '08005': {
    cityFips: '08005',
    cityName: 'Arapahoe County',
    state: 'CO',
    portalType: 'arcgis',
    downloadUrl: 'https://services2.arcgis.com/qzGaVFGfQxn25AYB/arcgis/rest/services/Inverness_Permits_Area/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 75,
    discoveredBy: 'automated',
    notes: 'Arapahoe County CO - 1 districts, bulk ingested from "City_Council_Districts_portal"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '0454050': {
    cityFips: '0454050',
    cityName: 'Peoria',
    state: 'AZ',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/OR7AzQGyqIyUNS4h/arcgis/rest/services/USPS_Scenario/FeatureServer/2/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 63,
    discoveredBy: 'automated',
    notes: 'Peoria AZ - 1 districts, bulk ingested from "Council District"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '08059': {
    cityFips: '08059',
    cityName: 'Jefferson County',
    state: 'CO',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/04HiymDgLlsbhaV4/arcgis/rest/services/Chelsea_Collinge_hdrinc_com_HDR_Arvada_CO_Layers/FeatureServer/7/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 58,
    discoveredBy: 'automated',
    notes: 'Jefferson County CO - 1 districts, bulk ingested from "Arvada Council Districts"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '0602252': {
    cityFips: '0602252',
    cityName: 'Antioch',
    state: 'CA',
    portalType: 'arcgis',
    downloadUrl: 'https://services3.arcgis.com/42Dx6OWonqK9LoEE/arcgis/rest/services/Districts_WEBv1_pro/FeatureServer/22/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 55,
    discoveredBy: 'automated',
    notes: 'Antioch CA - 1 districts, bulk ingested from "City of Antioch - Council District 1"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '0608142': {
    cityFips: '0608142',
    cityName: 'Brentwood',
    state: 'CA',
    portalType: 'arcgis',
    downloadUrl: 'https://services3.arcgis.com/42Dx6OWonqK9LoEE/arcgis/rest/services/Districts_WEBv1_pro/FeatureServer/28/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 55,
    discoveredBy: 'automated',
    notes: 'Brentwood CA - 1 districts, bulk ingested from "City of Brentwood - Council District 1"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '0646114': {
    cityFips: '0646114',
    cityName: 'Martinez',
    state: 'CA',
    portalType: 'arcgis',
    downloadUrl: 'https://services3.arcgis.com/42Dx6OWonqK9LoEE/arcgis/rest/services/Districts_WEBv1_pro/FeatureServer/47/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 55,
    discoveredBy: 'automated',
    notes: 'Martinez CA - 1 districts, bulk ingested from "City of Martinez - Council District 1"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '0653070': {
    cityFips: '0653070',
    cityName: 'Oakley',
    state: 'CA',
    portalType: 'arcgis',
    downloadUrl: 'https://services3.arcgis.com/42Dx6OWonqK9LoEE/arcgis/rest/services/Districts_WEBv1_pro/FeatureServer/53/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 55,
    discoveredBy: 'automated',
    notes: 'Oakley CA - 1 districts, bulk ingested from "City of Oakley - Council District 1"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '0668378': {
    cityFips: '0668378',
    cityName: 'San Ramon',
    state: 'CA',
    portalType: 'arcgis',
    downloadUrl: 'https://services3.arcgis.com/42Dx6OWonqK9LoEE/arcgis/rest/services/Districts_WEBv1_pro/FeatureServer/74/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 55,
    discoveredBy: 'automated',
    notes: 'San Ramon CA - 1 districts, bulk ingested from "City of San Ramon - Council District 1"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '0633182': {
    cityFips: '0633182',
    cityName: 'Hemet',
    state: 'CA',
    portalType: 'arcgis',
    downloadUrl: 'https://services3.arcgis.com/czrgcV6qkPuBJCRH/arcgis/rest/services/Hemet_Council_Districts/FeatureServer/1/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 55,
    discoveredBy: 'automated',
    notes: 'Hemet CA - 1 districts, bulk ingested from "Hemet_Council_District2"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '0670000': {
    cityFips: '0670000',
    cityName: 'Santa Monica',
    state: 'CA',
    portalType: 'arcgis',
    downloadUrl: 'https://services2.arcgis.com/LMBdfutQCnDGYUyc/arcgis/rest/services/Council_District_11_shp/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 55,
    discoveredBy: 'automated',
    notes: 'Santa Monica CA - 1 districts, bulk ingested from "Council_District_11_shp"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '0613756': {
    cityFips: '0613756',
    cityName: 'Claremont',
    state: 'CA',
    portalType: 'arcgis',
    downloadUrl: 'https://services.arcgis.com/hVnyNvwbpFFPDV5j/arcgis/rest/services/Claremont_City_Council_Distrticst_2022/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 55,
    discoveredBy: 'automated',
    notes: 'Claremont CA - 1 districts, bulk ingested from "Claremont_City_Council_Distrticst_2022"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },

  '06065': {
    cityFips: '06065',
    cityName: 'Riverside County',
    state: 'CA',
    portalType: 'arcgis',
    downloadUrl: 'https://services3.arcgis.com/czrgcV6qkPuBJCRH/arcgis/rest/services/Hemet_Council_Districts/FeatureServer/3/query?where=1%3D1&outFields=*&f=geojson',
    featureCount: 1,
    lastVerified: '2026-01-15T00:00:00.000Z',
    confidence: 50,
    discoveredBy: 'automated',
    notes: 'Riverside County CA - 1 districts, bulk ingested from "Hemet_Council_District4"',
    quarantineReason: 'SINGLE_FEATURE - Only 1 feature, cannot tessellate city into districts',
    matchedPattern: 'single-feature',
    quarantinedAt: '2026-01-16T00:00:00.000Z',
  },
};
