// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

/// @title IDebateWeightVerifier
/// @notice Interface for verifying debate_weight ZK proofs on-chain
/// @dev The actual verifier is generated by bb.js getSolidityVerifier() from the
///      debate_weight circuit. This interface decouples the contract from the verifier.
///
/// CIRCUIT PUBLIC INPUTS:
///   [0] weighted_amount  — sqrt(stakeAmount) * tierMultiplier(engagementTier), proven in-circuit
///   [1] note_commitment  — Poseidon2(argumentIndex, weightedAmount, randomness), the position note commitment
///
/// The circuit proves, in zero-knowledge, that the prover knows:
///   - A raw stakeAmount and engagementTier whose combination yields weightedAmount
///   - A randomness value used to construct the note commitment
/// Without revealing stakeAmount, engagementTier, or randomness on-chain.
interface IDebateWeightVerifier {
    /// @notice Verify a debate_weight UltraHonk proof
    /// @param proof Serialized UltraHonk proof bytes (generated by bb.js)
    /// @param publicInputs Array of public inputs where:
    ///        [0] weighted_amount — proven weighted trade quantity (as bytes32)
    ///        [1] note_commitment — Poseidon2 commitment for position note construction
    /// @return True if the proof is valid, false otherwise
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view returns (bool);
}
