// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

/// @title IPositionNoteVerifier
/// @notice Interface for verifying position_note ZK proofs on-chain
/// @dev The actual verifier is generated by bb.js getSolidityVerifier() from the
///      position_note circuit. This interface decouples the contract from the verifier.
///
/// CIRCUIT PUBLIC INPUTS:
///   [0] position_root           — Merkle root of the position tree (built off-chain by shadow-atlas)
///   [1] nullifier               — Unique nullifier for this position claim (prevents double-spend)
///   [2] debate_id               — The bytes32 debate identifier (domain-separation)
///   [3] winning_argument_index  — Index of the winning argument (must match debate resolution)
///   [4] claimed_weighted_amount — The prover's weighted trade amount from their position note
///
/// The circuit proves, in zero-knowledge, that the prover knows:
///   - A position note leaf that exists in the position Merkle tree (Merkle membership proof)
///   - The note's argument index matches the claimed winning argument
///   - The note's weighted amount matches the claimed amount
///   - The nullifier is correctly derived from the note's secret randomness
/// Without revealing which leaf, or the randomness used in the commitment.
///
/// SETTLEMENT SEMANTICS (Phase 2):
///   settlePrivatePosition is an attestation function — it proves and records that a user
///   held a valid winning position without revealing their identity or position size.
///   Token settlement (proportional payout) is deferred to Phase 4 (Flow Encryption).
interface IPositionNoteVerifier {
    /// @notice Verify a position_note UltraHonk proof
    /// @param proof Serialized UltraHonk proof bytes (generated by bb.js)
    /// @param publicInputs Array of public inputs where:
    ///        [0] position_root           — Merkle root that includes the prover's note leaf
    ///        [1] nullifier               — Unique spend tag for this position claim
    ///        [2] debate_id               — bytes32 debate identifier for domain separation
    ///        [3] winning_argument_index  — Argument index the prover claims won
    ///        [4] claimed_weighted_amount — Trade weight the prover claims to have held
    /// @return True if the proof is valid, false otherwise
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view returns (bool);
}
